[package]
name = "matrix-pickle"
version = "0.1.0"
edition = "2021"

[features]
derive = ["dep:matrix-pickle-derive"]
default = ["derive"]

[dependencies]
thiserror = "1.0.37"
matrix-pickle-derive = { path = "../matrix-pickle-derive", optional = true}

[dev-dependencies]
proptest = "1.0.0"
